# Generated by Django 5.2.11 on 2026-03-27 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('fase_atual', models.CharField(default='pre_fase', help_text='pre_fase, capitulo_1, capitulo_2, etc', max_length=50, verbose_name='Fase Atual')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('concluida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Caminho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cor', models.CharField(default='azul', max_length=50, verbose_name='Cor')),
                ('dificuldade', models.CharField(default='médio', max_length=50, verbose_name='Dificuldade')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caminhos', to='polls.capitulo', verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'Caminho',
                'verbose_name_plural': 'Caminhos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(verbose_name='Ordem')),
                ('tipo_pista', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio')], default='text', max_length=10, verbose_name='Tipo de Pista')),
                ('conteudo_pista', models.TextField(verbose_name='Conteúdo da Pista')),
                ('resposta_correta', models.CharField(max_length=500, verbose_name='Resposta Correta')),
                ('caminho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='polls.caminho', verbose_name='Caminho')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['ordem'],
                'unique_together': {('caminho', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('pontuacao_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pontuação Total')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='polls.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(help_text='pre_fase, capitulo_1, capitulo_2, etc', max_length=50, verbose_name='Fase')),
                ('sigla', models.CharField(help_text='Ex: CLI (clique), DRA (arrastar), TIP (digitar), SEL (selecionar), ENV (enviar)', max_length=3, verbose_name='Sigla da Ação')),
                ('tipo', models.CharField(choices=[('click', 'Clique'), ('drag', 'Arrastar'), ('type', 'Digitar'), ('select', 'Selecionar'), ('submit', 'Enviar'), ('next', 'Avançar'), ('back', 'Voltar'), ('hint', 'Pedir Dica'), ('skip', 'Pular')], max_length=10, verbose_name='Tipo da Ação')),
                ('resposta', models.TextField(blank=True, help_text='Resposta dada pelo usuário ou ação realizada', null=True, verbose_name='Resposta')),
                ('tempo_reacao', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo em segundos entre apresentação do desafio e resposta', max_digits=8, null=True, verbose_name='Tempo de Reação (s)')),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Pontuação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='polls.crianca', verbose_name='Criança')),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='polls.desafio', verbose_name='Desafio')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='polls.sessao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['-created_at'],
            },
        ),
    ]
