# Generated by Django 5.2.11 on 2026-03-03 22:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, help_text='Nome da escola/instituição da criança', max_length=200, null=True, verbose_name='Instituição')),
                ('nome', models.CharField(help_text='Nome da criança', max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(help_text='Idade da criança em anos', verbose_name='Idade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da tarefa', max_length=200, verbose_name='Título')),
                ('concluida', models.BooleanField(default=False, help_text='Marque se a tarefa já foi concluída', verbose_name='Concluída?')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a tarefa foi criada', verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data em que a tarefa foi concluída', null=True, verbose_name='Data de Conclusão')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(blank=True, help_text='Instituição da criança no momento da sessão', max_length=200, null=True, verbose_name='Instituição')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='polls.crianca', verbose_name='Criança')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
