# Generated by Django 5.2.11 on 2026-03-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='tempo_reacao',
        ),
        migrations.AddField(
            model_name='acao',
            name='tempo_resposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tempo em segundos entre apresentação do desafio e resposta do usuário', max_digits=8, null=True, verbose_name='Tempo de Resposta (s)'),
        ),
    ]
