# Generated by Django 5.2.11 on 2026-03-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do capítulo', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do capítulo', null=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do capítulo', verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Caminho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do caminho', max_length=200, verbose_name='Nome')),
                ('cor', models.CharField(default='azul', help_text='Cor para identificação visual (ex: "vermelho", "#FF0000")', max_length=50, verbose_name='Cor')),
                ('dificuldade', models.CharField(default='médio', help_text='Nível de dificuldade (fácil, médio, difícil)', max_length=50, verbose_name='Dificuldade')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do caminho', verbose_name='Ordem')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caminhos', to='polls.capitulo', verbose_name='Capítulo')),
            ],
            options={
                'verbose_name': 'Caminho',
                'verbose_name_plural': 'Caminhos',
                'ordering': ['capitulo__ordem', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem do desafio dentro do caminho', verbose_name='Ordem')),
                ('tipo_pista', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio')], default='text', max_length=10, verbose_name='Tipo de Pista')),
                ('conteudo_pista', models.TextField(help_text='Texto, URL da imagem ou áudio', verbose_name='Conteúdo da Pista')),
                ('resposta_correta', models.CharField(help_text='Resposta esperada para o desafio', max_length=500, verbose_name='Resposta Correta')),
                ('caminho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios', to='polls.caminho', verbose_name='Caminho')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['caminho__ordem', 'ordem'],
                'unique_together': {('caminho', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_dada', models.CharField(help_text='Resposta fornecida pelo aluno', max_length=500, verbose_name='Resposta Dada')),
                ('acertou', models.BooleanField(help_text='Se o aluno acertou o desafio', verbose_name='Acertou?')),
                ('pontos', models.IntegerField(default=0, help_text='Pontuação obtida', verbose_name='Pontos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='polls.crianca', verbose_name='Aluno')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='polls.desafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-created_at'],
                'unique_together': {('aluno', 'desafio')},
            },
        ),
    ]
