# Generated by Django 5.2.11 on 2026-02-24 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da tarefa', max_length=200, verbose_name='Título')),
                ('concluida', models.BooleanField(default=False, help_text='Marque se a tarefa já foi concluída', verbose_name='Concluída?')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora em que a tarefa foi criada', verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data em que a tarefa foi concluída (preenchido automaticamente)', null=True, verbose_name='Data de Conclusão')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
