# Generated by Django 5.2.11 on 2026-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_acao_tempo_reacao_acao_tempo_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='tempo_reacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tempo entre o estímulo e o início da resposta do usuário', max_digits=8, null=True, verbose_name='Tempo de Reação (s)'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tempo_resposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tempo total para completar a ação (inclui tempo de reação)', max_digits=8, null=True, verbose_name='Tempo de Resposta (s)'),
        ),
    ]
