# Generated by Django 5.2.11 on 2026-03-23 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_capitulo_caminho_desafio_interacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFaseDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(help_text='Ordem do desafio na pré-fase', verbose_name='Ordem')),
                ('tipo_pista', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio')], default='text', max_length=10, verbose_name='Tipo de Pista')),
                ('conteudo_pista', models.TextField(help_text='Texto, URL da imagem ou áudio', verbose_name='Conteúdo da Pista')),
                ('resposta_correta', models.CharField(help_text='Resposta esperada para o desafio', max_length=500, verbose_name='Resposta Correta')),
                ('dica', models.TextField(blank=True, help_text='Dica para ajudar o aluno', null=True, verbose_name='Dica')),
            ],
            options={
                'verbose_name': 'Desafio da Pré-Fase',
                'verbose_name_plural': 'Desafios da Pré-Fase',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='crianca',
            name='fase_atual',
            field=models.CharField(default='pre_fase', help_text='Fase atual do aluno (pre_fase, capitulo_1, capitulo_2, etc)', max_length=50, verbose_name='Fase Atual'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='progresso_pre_fase',
            field=models.IntegerField(default=0, help_text='Quantidade de desafios concluídos na pré-fase', verbose_name='Progresso Pré-Fase'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='total_pre_fase',
            field=models.IntegerField(default=5, help_text='Total de desafios necessários para completar a pré-fase', verbose_name='Total Pré-Fase'),
        ),
        migrations.CreateModel(
            name='InteracaoPreFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_dada', models.CharField(max_length=500, verbose_name='Resposta Dada')),
                ('acertou', models.BooleanField(verbose_name='Acertou?')),
                ('tentativas', models.IntegerField(default=1, verbose_name='Número de Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_pre_fase', to='polls.crianca', verbose_name='Aluno')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='polls.prefasedesafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Interação Pré-Fase',
                'verbose_name_plural': 'Interações Pré-Fase',
                'ordering': ['-created_at'],
                'unique_together': {('aluno', 'desafio')},
            },
        ),
    ]
