# Generated by Django 5.2.11 on 2026-02-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, help_text='Data em que a tarefa foi concluída', null=True, verbose_name='Data de Conclusão'),
        ),
    ]
