# Generated by Django 5.2.11 on 2026-04-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_acao_tempo_reacao_alter_acao_tempo_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='resposta_correta',
        ),
        migrations.AlterField(
            model_name='acao',
            name='sigla',
            field=models.CharField(help_text='Ex: CLI, DRA, TIP, SEL, ENV, AVN, VOL, DIC, PUL', max_length=3, verbose_name='Sigla da Ação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tempo_reacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tempo entre o estímulo e o início da resposta', max_digits=8, null=True, verbose_name='Tempo de Reação (s)'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tempo_resposta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tempo total para completar a ação', max_digits=8, null=True, verbose_name='Tempo de Resposta (s)'),
        ),
    ]
