# Generated by Django 5.2.11 on 2026-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_desafio_resposta_correta_alter_acao_sigla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
