# Generated by Django 5.2.11 on 2026-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='jogo',
            field=models.CharField(blank=True, help_text='piaget, volta_casa, volta_casa_cog', max_length=30, null=True, verbose_name='Jogo'),
        ),
        migrations.AddField(
            model_name='acao',
            name='nivel',
            field=models.IntegerField(blank=True, help_text='1, 2 ou 3 (preenchido automaticamente pelo mapa)', null=True, verbose_name='Nível do Marcador'),
        ),
        migrations.AddField(
            model_name='acao',
            name='resposta_chave',
            field=models.CharField(blank=True, help_text='Identificador da opção escolhida (ex: certa, adjacente, longe)', max_length=100, null=True, verbose_name='Chave da Resposta'),
        ),
        migrations.AddField(
            model_name='acao',
            name='rotulo',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente pelo mapa', max_length=200, null=True, verbose_name='Rótulo Qualitativo'),
        ),
        migrations.AddField(
            model_name='acao',
            name='valor_marcador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido automaticamente pelo mapa', max_digits=8, null=True, verbose_name='Valor do Marcador'),
        ),
        migrations.CreateModel(
            name='MapaMarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogo', models.CharField(choices=[('piaget', 'Jogo Piaget'), ('volta_casa', 'De volta pra casa'), ('volta_casa_cog', 'De volta pra casa - Cognitivo')], max_length=30, verbose_name='Jogo')),
                ('fase', models.CharField(help_text='Identificador da tela/fase (deve casar com Acao.fase)', max_length=100, verbose_name='Fase / Tela')),
                ('resposta_chave', models.CharField(help_text='Identificador estável da opção (ex: certa, adjacente, longe)', max_length=100, verbose_name='Chave da Resposta')),
                ('sigla', models.CharField(blank=True, default='', max_length=3, verbose_name='Sigla da Ação')),
                ('nivel', models.IntegerField(blank=True, help_text='1, 2 ou 3 (jogos por nível). Vazio nos jogos dimensionais.', null=True, verbose_name='Nível')),
                ('rotulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Rótulo Qualitativo')),
                ('valor_quantitativo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Quantitativo (Marcador)')),
                ('descricao_qualitativa', models.TextField(blank=True, null=True, verbose_name='Descrição Qualitativa')),
            ],
            options={
                'verbose_name': 'Mapa de Marcador',
                'verbose_name_plural': 'Mapa de Marcadores',
                'ordering': ['jogo', 'fase', '-nivel'],
                'unique_together': {('jogo', 'fase', 'resposta_chave')},
            },
        ),
    ]
