# Generated by Django 5.2.11 on 2026-07-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_acao_jogo_acao_nivel_acao_resposta_chave_acao_rotulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapamarcador',
            options={'ordering': ('jogo', 'fase', 'resposta_chave'), 'verbose_name': 'Mapa Marcador', 'verbose_name_plural': 'Mapa Marcadores'},
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='descricao_qualitativa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='fase',
            field=models.CharField(max_length=100, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='jogo',
            field=models.CharField(max_length=50, verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='resposta_chave',
            field=models.CharField(max_length=200, verbose_name='Resposta Chave'),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='rotulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='mapamarcador',
            name='valor_quantitativo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
